# Generated by Django 6.1.1 on 2026-09-29 11:07

import apps.core.phones
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='Institution')),
                ('educational_session', models.CharField(blank=True, max_length=100, verbose_name='Educational Session')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.classlevel')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='GuardianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name="Guardian's Name")),
                ('phone', models.CharField(blank=True, max_length=20, validators=[apps.core.phones.validate_phone], verbose_name="Guardian's Phone Number")),
                ('relation', models.CharField(blank=True, max_length=50, verbose_name='Relation')),
                ('occupation', models.CharField(blank=True, max_length=150, verbose_name='Occupation')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to='profiles.studentprofile')),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=150, verbose_name='Designation')),
                ('description', models.TextField(blank=True, verbose_name='Bio')),
                ('experience', models.CharField(blank=True, max_length=255, verbose_name='Experience')),
                ('institute', models.CharField(blank=True, max_length=255, verbose_name='Institution')),
                ('type', models.CharField(choices=[('permanent', 'Permanent Teacher'), ('guest', 'Guest Teacher')], default='permanent', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('levels', models.ManyToManyField(blank=True, related_name='teachers', to='academic.classlevel')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='academic.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
