# Generated by Django 5.0.14 on 2026-08-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', '-created_at'], name='accounts_ot_phone_9473c1_idx'),
        ),
    ]
