# Generated by Django 6.1.1 on 2026-10-07 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_payment_product'),
        ('materials', '0002_move_ebooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.CharField(choices=[('sylhet', 'Inside Sylhet'), ('outside', 'Outside Sylhet')], max_length=20, unique=True)),
                ('charge', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-zone'],
            },
        ),
        migrations.AddField(
            model_name='materialitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('zone', models.CharField(choices=[('sylhet', 'Inside Sylhet'), ('outside', 'Outside Sylhet')], max_length=20)),
                ('book_price', models.PositiveIntegerField()),
                ('delivery_charge', models.PositiveIntegerField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='materials.materialitem')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_order', to='billing.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
