# Generated by Django 6.1.1 on 2026-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=64, unique=True, verbose_name='Transaction ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('access_until', models.DateTimeField(blank=True, null=True, verbose_name='Access Until')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('VALID', 'Valid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='INITIATED', max_length=16, verbose_name='Status')),
                ('card_type', models.CharField(blank=True, max_length=64, verbose_name='Card Type')),
                ('card_issuer_country', models.CharField(blank=True, max_length=64, verbose_name='Card Issuer Country')),
                ('transaction_date', models.DateTimeField(blank=True, null=True, verbose_name='Transaction Date')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Gateway Response')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('product_id', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='Product ID')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('base_price', models.PositiveIntegerField(verbose_name='Base Price')),
                ('access_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Access Days')),
                ('access_ends_on', models.DateField(blank=True, null=True, verbose_name='Access Ends On')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['id'],
            },
        ),
    ]
