# Generated by Django 6.1.1 on 2026-10-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Discount Ends At'),
        ),
    ]
