# Generated by Django 6.1.1 on 2026-10-04 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_product_discount_ends_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmation Sent At'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], default='online', max_length=16, verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By'),
        ),
    ]
