# Generated by Django 5.0.14 on 2026-08-16 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
        ('courses', '0003_content_courses_con_course__894dd2_idx_and_more'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'course'], name='billing_ord_user_id_6ad383_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='billing_ord_status_5ce6d5_idx'),
        ),
    ]
