# Generated by Django 6.1.1 on 2026-10-05 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_page_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Gateway Page'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_due',
            field=models.BooleanField(default=False, verbose_name='Refund Due'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='billing_pay_status_f64990_idx'),
        ),
    ]
