# Generated by Django 5.0.14 on 2026-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('positive_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Seconds spent on the attempt')),
                ('submitted', models.BooleanField(default=True)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('attachment', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-marks', 'duration'],
            },
        ),
        migrations.CreateModel(
            name='McqQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('question_image', models.URLField(blank=True, null=True)),
                ('a', models.TextField(blank=True, null=True)),
                ('b', models.TextField(blank=True, null=True)),
                ('c', models.TextField(blank=True, null=True)),
                ('d', models.TextField(blank=True, null=True)),
                ('e', models.TextField(blank=True, null=True)),
                ('answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1)),
                ('answer_image', models.URLField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('source_year', models.CharField(blank=True, max_length=20)),
                ('source_board', models.CharField(blank=True, max_length=100)),
                ('source_topic', models.CharField(blank=True, max_length=150)),
                ('source_chapter', models.CharField(blank=True, max_length=150)),
                ('source_college', models.CharField(blank=True, max_length=150)),
                ('source_subject', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='McqStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
