# Generated by Django 5.0.14 on 2026-08-16 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', '-marks', 'duration'], name='assessment__exam_id_d582a5_idx'),
        ),
    ]
