# Generated by Django 6.1.1 on 2026-10-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_seed_home_pages'),
        # Its rows become study material book items first.
        ('materials', '0002_move_ebooks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EBook',
        ),
    ]
