# Generated by Django 6.1.1 on 2026-09-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_seed_home_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='noticecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug'),
        ),
    ]
