# Generated by Django 6.1.1 on 2026-10-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_delete_ebook'),
        # Notices move to `communication`, which copies them before these tables go.
        ('communication', '0002_copy_old_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticecategory',
            name='notice_category',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='NoticeCategory',
        ),
    ]
