# Generated by Django 6.1.1 on 2026-09-29 11:07

import apps.core.phones
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('code', models.CharField(max_length=8, verbose_name='Code')),
                ('purpose', models.CharField(choices=[('verify', 'Phone Verification'), ('password_reset', 'Password Reset')], default='verify', max_length=20, verbose_name='Purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Issued At')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='Consumed At')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Failed Attempts')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Request Meta')),
            ],
            options={
                'verbose_name': 'One-time Code',
                'verbose_name_plural': 'One-time Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', '-created_at'], name='identity_ot_phone_dec55c_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[apps.core.phones.validate_phone], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Full Name')),
                ('image', models.URLField(blank=True, verbose_name='Profile Image')),
                ('fcm_token', models.CharField(blank=True, max_length=255, verbose_name='FCM Token')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Phone Verified At')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Verified At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['-date_joined'], name='identity_us_date_jo_11e73c_idx')],
            },
        ),
    ]
