# Generated by Django 6.1.1 on 2026-10-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_seed_role_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='At')),
            ],
            options={
                'verbose_name': 'Failed Sign-in',
                'verbose_name_plural': 'Failed Sign-ins',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='identity_lo_phone_a59be7_idx')],
            },
        ),
    ]
