# Generated by Django 5.0.14 on 2026-08-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_normalize_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
