# Generated by Django 6.1.1 on 2026-10-06 11:29

import apps.courses.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='slug')),
                ('type', models.CharField(choices=[('video', 'Video'), ('note', 'Note'), ('pdf', 'PDF'), ('exam', 'Exam'), ('link', 'Link'), ('live', 'Live')], max_length=20)),
                ('variant', models.CharField(choices=[('New', 'New'), ('Update', 'Update'), ('Revision', 'Revision')], default='New', max_length=20)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('video_source', models.CharField(blank=True, default='youtube', max_length=20)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('video_description', models.TextField(blank=True)),
                ('video_embedded', models.BooleanField(default=True)),
                ('video_cipher', models.BooleanField(default=False)),
                ('note_body', models.TextField(blank=True)),
                ('pdf_file', models.URLField(blank=True, null=True)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('live_scheduled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='slug')),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('delivery', models.CharField(choices=[('live', 'Live'), ('recorded', 'Recorded'), ('hybrid', 'Live + recorded')], default='recorded', max_length=20)),
                ('is_online', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('bn', 'Bangla'), ('en', 'English'), ('mixed', 'Bangla & English')], default='bn', max_length=10)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('fake_student_count', models.PositiveIntegerField(default=0)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('enrollment_deadline', models.DateTimeField(blank=True, null=True)),
                ('schedule_note', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('banner', models.URLField(blank=True, null=True)),
                ('promo_video', models.URLField(blank=True, null=True)),
                ('syllabus_pdf', models.URLField(blank=True, null=True)),
                ('learning_outcomes', models.JSONField(blank=True, default=list, validators=[apps.courses.validators.ItemListValidator(required=['title', 'icon'])])),
                ('target_audience', models.JSONField(blank=True, default=list, validators=[apps.courses.validators.ItemListValidator(required=['title'])])),
                ('requirements', models.JSONField(blank=True, default=list, validators=[apps.courses.validators.ItemListValidator(required=['title'])])),
                ('highlights', models.JSONField(blank=True, default=list, validators=[apps.courses.validators.ItemListValidator(optional=['description'], required=['title', 'icon'])])),
                ('faqs', models.JSONField(blank=True, default=list, validators=[apps.courses.validators.ItemListValidator(required=['question', 'answer'])])),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('file', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, help_text='Percent of each sale of this course paid to this teacher. Recorded only -- nothing computes a payout from it yet.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('subscription', 'Subscription')], default='free', max_length=20)),
                ('expiry_reminded_for', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='slug')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.content')),
            ],
        ),
    ]
