# Generated by Django 5.0.14 on 2026-08-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('is_online', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('fake_user_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('video', models.URLField(blank=True, null=True)),
                ('pdf_link', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('type', models.CharField(choices=[('video', 'Video'), ('note', 'Note'), ('pdf', 'PDF'), ('exam', 'Exam'), ('link', 'Link'), ('live', 'Live')], max_length=20)),
                ('variant', models.CharField(choices=[('New', 'New'), ('Update', 'Update'), ('Revision', 'Revision'), ('Draft', 'Draft')], default='New', max_length=20)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('video_source', models.CharField(blank=True, default='youtube', max_length=20)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('video_description', models.TextField(blank=True)),
                ('video_embedded', models.BooleanField(default=True)),
                ('video_cipher', models.BooleanField(default=False)),
                ('note_body', models.TextField(blank=True)),
                ('pdf_file', models.URLField(blank=True, null=True)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('live_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.coursecategory')),
            ],
            options={
                'verbose_name_plural': 'course categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.coursecategory'),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('file', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priceable_type', models.CharField(choices=[('course', 'Course')], default='course', max_length=50)),
                ('priceable_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_till', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('subscription', 'Subscription')], default='full', max_length=20)),
                ('validity_type', models.CharField(choices=[('absolute', 'Absolute'), ('relative', 'Relative')], default='relative', max_length=20)),
                ('validity_time', models.DateTimeField(blank=True, null=True)),
                ('validity_duration', models.PositiveIntegerField(blank=True, help_text='Validity length in days (relative validity)', null=True)),
            ],
            options={
                'ordering': ['amount'],
                'indexes': [models.Index(fields=['priceable_type', 'priceable_id'], name='courses_cou_priceab_d7de5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', max_length=20)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='courses.courseprice')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('subscription', 'Subscription')], default='free', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
            ],
        ),
    ]
