# Generated by Django 6.1.1 on 2026-10-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='section',
            name='slug',
        ),
    ]
