# Generated by Django 5.0.14 on 2026-07-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprice',
            name='course',
        ),
        migrations.AddField(
            model_name='courseprice',
            name='priceable_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseprice',
            name='priceable_type',
            field=models.CharField(choices=[('course', 'Course')], default='course', max_length=50),
        ),
        migrations.AddIndex(
            model_name='courseprice',
            index=models.Index(fields=['priceable_type', 'priceable_id'], name='courses_cou_priceab_d7de5a_idx'),
        ),
    ]
