# Generated by Django 5.0.14 on 2026-08-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['course', 'type'], name='courses_con_course__894dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['course', 'active'], name='courses_con_course__659027_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['active', 'featured'], name='courses_cou_active_bec911_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['course', 'active'], name='courses_sec_course__87872d_idx'),
        ),
    ]
