# Generated by Django 6.1.1 on 2026-09-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
