# Generated by Django 6.1.1 on 2026-10-01 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('academic', '0001_initial'),
        ('courses', '0003_remove_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='courses',
                to='academic.batch',
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='class_level',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='courses',
                to='academic.classlevel',
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='courses',
                to='academic.group',
            ),
        ),
    ]
