# Generated by Django 6.1.1 on 2026-10-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_drop_section_content_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='expiry_notice_sent_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
