# Generated by Django 6.1.1 on 2026-10-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_expiry_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
    ]
