# Generated by Django 6.1.1 on 2026-10-08 10:30

import apps.core.fields
from django.db import migrations

from apps.core.text.html import clean_html

HTML_FIELDS = {"Course": ("description",), "Content": ("note_body", "video_description")}


def clean_stored_html(apps, schema_editor):
    """Rows written through Django's admin before this skipped the API's cleaning."""
    for model_name, fields in HTML_FIELDS.items():
        model = apps.get_model("courses", model_name)
        for row in model.objects.only("pk", *fields).iterator():
            cleaned = {field: clean_html(getattr(row, field)) for field in fields}
            if any(cleaned[field] != getattr(row, field) for field in fields):
                model.objects.filter(pk=row.pk).update(**cleaned)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_delete_course_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='note_body',
            field=apps.core.fields.HtmlTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='video_description',
            field=apps.core.fields.HtmlTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=apps.core.fields.HtmlTextField(blank=True),
        ),
        migrations.RunPython(clean_stored_html, migrations.RunPython.noop),
    ]
