# Generated by Django 6.1.1 on 2026-10-01 11:32

import apps.courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('courses', '0005_course_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banner',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='delivery',
            field=models.CharField(choices=[('live', 'Live'), ('recorded', 'Recorded'), ('hybrid', 'Live + recorded')], default='recorded', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='faqs',
            field=models.JSONField(blank=True, default=list, validators=[apps.courses.validators.ItemListValidator(required=['question', 'answer'])]),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('bn', 'Bangla'), ('en', 'English'), ('mixed', 'Bangla & English')], default='bn', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=list, validators=[apps.courses.validators.ItemListValidator(required=['title', 'icon'])]),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='course',
            name='og_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.JSONField(blank=True, default=list, validators=[apps.courses.validators.ItemListValidator(required=['title'])]),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='starts_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.JSONField(blank=True, default=list, validators=[apps.courses.validators.ItemListValidator(required=['title'])]),
        ),
        migrations.AlterField(
            model_name='course',
            name='highlights',
            field=models.JSONField(blank=True, default=list, validators=[apps.courses.validators.ItemListValidator(required=['title', 'description', 'icon'])]),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'is_featured'], name='courses_cou_status_ee4b06_idx'),
        ),
    ]
