# Generated by Django 6.1.1 on 2026-10-04 09:20

import apps.courses.validators
from django.db import migrations, models


ICON_KEYWORDS = [
    ("wallet", ("৳", "পেমেন্ট", "টাকা", "payment")),
    ("video", ("লাইভ", "ভিডিও", "ক্লাস", "live", "video", "class")),
    ("trophy", ("পরীক্ষা", "র‍্যাঙ্ক", "এমসিকিউ", "exam", "rank", "mcq")),
    ("file-text", ("পিডিএফ", "শিট", "নোট", "pdf", "sheet", "note")),
    ("message-circle", ("সাপোর্ট", "গ্রুপ", "প্রশ্ন", "support", "group")),
]


def icon_for(title):
    text = title.lower()
    return next((icon for icon, words in ICON_KEYWORDS if any(w in text for w in words)), "circle-check")


def fill_icons(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    for course in Course.objects.exclude(highlights=[]):
        changed = False
        for item in course.highlights:
            if not item.get("icon"):
                item["icon"] = icon_for(item.get("title", ""))
                changed = True
            if "description" in item and not item["description"]:
                del item["description"]
                changed = True
        if changed:
            course.save(update_fields=["highlights"])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_prices_to_packages'),
    ]

    operations = [
        migrations.RunPython(fill_icons, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='highlights',
            field=models.JSONField(blank=True, default=list, validators=[apps.courses.validators.ItemListValidator(optional=['description'], required=['title', 'icon'])]),
        ),
    ]
