# Generated by Django 6.1.1 on 2026-10-04 10:32

from django.db import migrations, models


def hide_drafts(apps, schema_editor):
    Content = apps.get_model("courses", "Content")
    Content.objects.filter(variant="Draft").update(variant="New", active=False)


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0009_clean_rich_text'),
    ]

    operations = [
        migrations.RunPython(hide_drafts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='content',
            name='variant',
            field=models.CharField(
                choices=[('New', 'New'), ('Update', 'Update'), ('Revision', 'Revision')], default='New', max_length=20
            ),
        ),
    ]
