# Generated by Django 6.1.1 on 2026-10-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_draft_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='expiry_reminded_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
