# Generated by Django 6.1.1 on 2026-10-05 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_enrollment_expiry_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['valid_till'], name='courses_enr_valid_t_72324d_idx'),
        ),
    ]
