# Generated by Django 6.1.1 on 2026-10-08 04:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_delete_course_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('course', 'Course'), ('general', 'General')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('image', models.URLField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('hidden', 'Hidden')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['source', 'status'], name='feedback_fe_source_b49df8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('source', 'course')), models.Q(models.Q(('source', 'course'), _negated=True), ('course__isnull', True)), _connector='OR'), name='feedback_course_matches_source'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='feedback_rating_1_to_5'), models.CheckConstraint(condition=models.Q(models.Q(('is_featured', True), _negated=True), ('status', 'approved'), _connector='OR'), name='feedback_featured_is_approved'), models.UniqueConstraint(condition=models.Q(('source', 'course')), fields=('author', 'course'), name='feedback_one_per_course'), models.UniqueConstraint(condition=models.Q(('source', 'general')), fields=('author',), name='feedback_one_general')],
            },
        ),
    ]
