# Generated by Django 6.1.1 on 2026-09-23 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('cq', 'Creative Question')], default='mcq', max_length=20)),
                ('marks', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Marks')),
                ('marks_per_question', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Marks Per Question')),
                ('negative_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Marks Per Wrong')),
                ('pass_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Pass Marks')),
                ('required_question_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Answers Required')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duration')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='Shuffle Questions')),
                ('shuffle_options', models.BooleanField(default=False, verbose_name='Shuffle Options')),
                ('question_count', models.PositiveSmallIntegerField(default=0, verbose_name='Question Count')),
                ('computed_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Computed Marks')),
            ],
            options={
                'verbose_name': 'Exam Section',
                'verbose_name_plural': 'Exam Sections',
                'ordering': ['exam_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Marks')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': 'Exam Questions',
                'ordering': ['section_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('scope', models.CharField(choices=[('standalone', 'Standalone'), ('batch', 'Batch')], default='standalone', max_length=20)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Total Marks')),
                ('pass_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Pass Marks')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duration')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Starts')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Ends')),
                ('result_publish_time', models.DateTimeField(blank=True, null=True, verbose_name='Results At')),
                ('max_attempts', models.PositiveSmallIntegerField(default=1, verbose_name='Max Attempts')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academic.batch')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
