# Generated by Django 6.1.1 on 2026-09-29 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('exam', '0001_initial'),
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examsection',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='examsection',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sections', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='examsectionquestion',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_usages', to='question.questionblock'),
        ),
        migrations.AddField(
            model_name='examsectionquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_questions', to='exam.examsection'),
        ),
        migrations.AddField(
            model_name='examsection',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='exam_sections', through='exam.ExamSectionQuestion', through_fields=('section', 'block'), to='question.questionblock'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status', 'start_time'], name='exam_exam_status_54d8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['created_by'], name='exam_exam_created_976a26_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['scope'], name='exam_exam_scope_9f3842_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('pass_marks__isnull', True), ('pass_marks__lte', models.F('total_marks')), _connector='OR'), name='exam_pass_marks_within_total'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='exam_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='exam_allows_one_attempt'),
        ),
        migrations.AddIndex(
            model_name='examsectionquestion',
            index=models.Index(fields=['section', 'order'], name='exam_examse_section_62cce3_idx'),
        ),
        migrations.AddIndex(
            model_name='examsectionquestion',
            index=models.Index(fields=['block'], name='exam_examse_block_i_fb4927_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsectionquestion',
            constraint=models.UniqueConstraint(fields=('section', 'block'), name='unique_block_per_exam_section'),
        ),
        migrations.AddIndex(
            model_name='examsection',
            index=models.Index(fields=['exam', 'order'], name='exam_examse_exam_id_2a6e48_idx'),
        ),
        migrations.AddIndex(
            model_name='examsection',
            index=models.Index(fields=['question_type'], name='exam_examse_questio_1f639d_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsection',
            constraint=models.UniqueConstraint(fields=('exam', 'title'), name='unique_section_title_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='examsection',
            constraint=models.CheckConstraint(condition=models.Q(('negative_marks__isnull', True), models.Q(('negative_marks__gte', 0), ('negative_marks__lte', models.F('marks_per_question'))), _connector='OR'), name='exam_section_negative_marks_within_rate'),
        ),
        migrations.AddConstraint(
            model_name='examsection',
            constraint=models.CheckConstraint(condition=models.Q(('pass_marks__isnull', True), models.Q(('pass_marks__gt', 0), ('pass_marks__lte', models.F('marks'))), _connector='OR'), name='exam_section_pass_marks_within_marks'),
        ),
    ]
