# Generated by Django 6.1.1 on 2026-10-07 10:14

from django.db import migrations, models
from django.db.models import Sum
from django.db.models.functions import Coalesce


def recompute_totals(apps, schema_editor):
    """Every exam is worth what its sections add up to."""
    Exam = apps.get_model("exam", "Exam")
    for exam in Exam.objects.annotate(
        sum_marks=Coalesce(Sum("sections__marks"), models.Value(0, output_field=models.DecimalField()))
    ):
        Exam.objects.filter(pk=exam.pk).update(total_marks=exam.sum_marks)


class Migration(migrations.Migration):
    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='exam_pass_marks_within_total',
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=6, verbose_name='Total Marks'
            ),
        ),
        migrations.RunPython(recompute_totals, migrations.RunPython.noop),
    ]
