# Generated by Django 6.1.1 on 2026-09-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug'),
        ),
    ]
