# Generated by Django 6.1.1 on 2026-10-01 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def exams_for_exam_lessons(apps, schema_editor):
    """Every existing exam lesson gets the draft exam a new one would get
    (`apps.exam.signals.create_course_exam`), so none is left without a paper.
    Historical models skip `save()`, so the slug is built here."""
    from django.utils.text import slugify

    Content = apps.get_model("courses", "Content")
    Exam = apps.get_model("exam", "Exam")
    taken = set(Exam.objects.values_list("slug", flat=True))
    for lesson in Content.objects.filter(type="exam", exam__isnull=True):
        slug = (slugify(lesson.title) or "exam")[:200]
        if slug in taken:
            slug = f"{slug[:190]}-l{lesson.pk}"
        taken.add(slug)
        Exam.objects.create(
            lesson=lesson, title=lesson.title[:200], slug=slug, scope="course", status="draft"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('courses', '0007_course_prices_to_packages'),
        ('exam', '0002_initial'),
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_option_ids', models.JSONField(default=list)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('seed', models.BigIntegerField()),
                ('started_at', models.DateTimeField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('correct', models.PositiveSmallIntegerField(default=0)),
                ('wrong', models.PositiveSmallIntegerField(default=0)),
                ('skipped', models.PositiveSmallIntegerField(default=0)),
                ('is_official', models.BooleanField(default=False)),
                ('marking', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='courses.content'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='scope',
            field=models.CharField(choices=[('standalone', 'Standalone'), ('batch', 'Batch'), ('course', 'Course')], default='standalone', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'course'), ('lesson__isnull', False)), models.Q(models.Q(('scope', 'course'), _negated=True), ('lesson__isnull', True)), _connector='OR'), name='exam_course_scope_has_lesson'),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_answers', to='question.question'),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='section_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='exam.examsectionquestion'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.examattempt'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'is_official', 'score'], name='exam_examat_exam_id_d5c9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'exam'], name='exam_examat_user_id_5d1a6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('exam', 'user', 'number'), name='unique_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='examanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_question'),
        ),
        migrations.RunPython(exams_for_exam_lessons, migrations.RunPython.noop),
    ]
