# Generated by Django 6.1.1 on 2026-10-07 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_derived_total_marks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='awaiting_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExamAnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('files', models.JSONField(default=list)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='exam.examattempt')),
                ('section_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_sheets', to='exam.examsectionquestion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'section_question'), name='unique_sheet_per_question')],
            },
        ),
    ]
