# Generated by Django 6.1.1 on 2026-10-05 12:56

from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Window
from django.db.models.functions import RowNumber


def demote_extra_official_attempts(apps, schema_editor):
    """Before the constraint: where a student has more than one official attempt, the earliest submitted stays."""
    ExamAttempt = apps.get_model("exam", "ExamAttempt")
    ranked = ExamAttempt.objects.filter(is_official=True).annotate(
        place=Window(
            RowNumber(),
            partition_by=[F("exam_id"), F("user_id")],
            order_by=[F("submitted_at").asc(nulls_last=True), F("id").asc()],
        )
    )
    extra = [attempt.pk for attempt in ranked if attempt.place > 1]
    ExamAttempt.objects.filter(pk__in=extra).update(is_official=False)


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_course_exams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(demote_extra_official_attempts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='examsectionquestion',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Marks'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status', 'deadline'], name='exam_examat_status_10f2bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_official', True)), fields=('exam', 'user'), name='one_official_attempt_per_exam'),
        ),
    ]
