# Generated by Django 5.0.14 on 2026-09-15 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('group_count', models.PositiveIntegerField(default=0, verbose_name='Group Count')),
                ('subject_count', models.PositiveIntegerField(default=0, verbose_name='Subject Count')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='Question Count')),
                ('chapter_count', models.PositiveIntegerField(default=0, verbose_name='Chapter Count')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Class Level',
                'verbose_name_plural': 'Class Levels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('subject_count', models.PositiveIntegerField(default=0, verbose_name='Subject Count')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='Question Count')),
                ('chapter_count', models.PositiveIntegerField(default=0, verbose_name='Chapter Count')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Academic Group',
                'verbose_name_plural': 'Academic Groups',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academic.classlevel', verbose_name='Education Level')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='Question Count')),
                ('chapter_count', models.PositiveIntegerField(default=0, verbose_name='Chapter Count')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.classlevel', verbose_name='Education Level')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.group', verbose_name='Academic Group')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('name', 'class_level'), name='unique_batch_per_level'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name', 'class_level', 'group'), name='unique_subject_per_level_and_group'),
        ),
    ]
