# Generated by Django 6.1.1 on 2026-10-06 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='Question Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Class Level',
                'verbose_name_plural': 'Class Levels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='Question Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='slug')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='Question Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academic.classlevel', verbose_name='Education Level')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academic.group')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('chapter_number', models.PositiveSmallIntegerField(default=0, verbose_name='Chapter Number')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='Question Count')),
                ('practice_enabled', models.BooleanField(default=False, help_text='Its questions, answers included, are served free to anyone on the practice page. Off until a teacher opens it, so questions written for an upcoming exam are not given away.', verbose_name='Open for Practice')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='academic.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['chapter_number', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='Question Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='academic.chapter', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='academic.classlevel', verbose_name='Education Level')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['order', 'name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('name', 'class_level'), name='unique_batch_per_level')],
            },
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name', 'class_level', 'group'), name='unique_subject_per_level_and_group'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['subject', 'chapter_number'], name='academic_ch_subject_9ba7a6_idx'),
        ),
    ]
