# Generated by Django 6.1.1 on 2026-10-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_common',
            field=models.BooleanField(default=False, help_text="Taken by every student on top of their own group, e.g. General (Bangla, English).", verbose_name='Common to Every Group'),
        ),
    ]
