# Generated by Django 6.1.1 on 2026-09-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug'),
        ),
    ]
