# Generated by Django 6.1.1 on 2026-10-04 10:34

from django.db import migrations, models


def number_topics(apps, schema_editor):
    Topic = apps.get_model("academic", "Topic")
    chapter, order = None, 0
    for topic in Topic.objects.order_by("chapter_id", "name", "id"):
        if topic.chapter_id != chapter:
            chapter, order = topic.chapter_id, 0
        if topic.order != order:
            topic.order = order
            topic.save(update_fields=["order"])
        order += 1


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'name', 'id'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.RunPython(number_topics, migrations.RunPython.noop),
    ]
