# Generated by Django 5.0.14 on 2026-09-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['order', 'name', 'id'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'name', 'id'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='academic.classlevel', verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academic.classlevel', verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academic.group', verbose_name='Academic Group'),
        ),
    ]
