# Generated by Django 5.0.14 on 2026-09-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_protect_and_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
