# Generated by Django 6.1.1 on 2026-09-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_batch_slug_alter_chapter_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='question_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Question Count'),
        ),
    ]
