# Generated by Django 6.1.1 on 2026-10-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_topic_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlevel',
            name='chapter_count',
        ),
        migrations.RemoveField(
            model_name='classlevel',
            name='group_count',
        ),
        migrations.RemoveField(
            model_name='classlevel',
            name='subject_count',
        ),
        migrations.RemoveField(
            model_name='group',
            name='chapter_count',
        ),
        migrations.RemoveField(
            model_name='group',
            name='subject_count',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='chapter_count',
        ),
    ]
