# Generated by Django 6.1.1 on 2026-10-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_live_structure_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='chapter',
            name='practice_enabled',
            field=models.BooleanField(default=False, help_text='Its questions, answers included, are served free to anyone on the practice page. Off until a teacher opens it, so questions written for an upcoming exam are not given away.', verbose_name='Open for Practice'),
        ),
    ]
