# Generated by Django 6.1.1 on 2026-10-07 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_group_is_common'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('notice_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='communication.noticecategory')),
            ],
            options={
                'verbose_name_plural': 'notice categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='slug')),
                ('body', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('batches', models.ManyToManyField(blank=True, related_name='notices', to='academic.batch')),
                ('class_levels', models.ManyToManyField(blank=True, related_name='notices', to='academic.classlevel')),
                ('categories', models.ManyToManyField(blank=True, related_name='notices', to='communication.noticecategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoticeSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notice_seen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('phone_verify', 'Phone verification'), ('password_reset', 'Password reset'), ('expiry_reminder', 'Expiry reminder'), ('access_ended', 'Access ended notice'), ('purchase', 'Purchase / renewal notice'), ('guardian', 'Message to a guardian'), ('custom', 'Custom message')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_received', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS message',
                'verbose_name_plural': 'SMS messages',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['purpose', 'created_at'], name='communicati_purpose_e3186e_idx'), models.Index(fields=['phone'], name='communicati_phone_1dc65d_idx')],
            },
        ),
    ]
