# Generated by Django 6.1.1 on 2026-10-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_copy_old_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticecategory',
            name='notice_category',
        ),
    ]
