# Generated by Django 6.1.1 on 2026-10-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_remove_notice_category_nesting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='slug',
        ),
    ]
