# Generated by Django 6.1.1 on 2026-10-08 10:30

import apps.core.fields
from django.db import migrations

from apps.core.text.html import clean_html


def clean_stored_html(apps, schema_editor):
    """Notices written through Django's admin before this skipped the API's cleaning."""
    notice = apps.get_model("communication", "Notice")
    for row in notice.objects.only("pk", "body").iterator():
        cleaned = clean_html(row.body)
        if cleaned != row.body:
            notice.objects.filter(pk=row.pk).update(body=cleaned)


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_remove_notice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=apps.core.fields.HtmlTextField(blank=True),
        ),
        migrations.RunPython(clean_stored_html, migrations.RunPython.noop),
    ]
