# Generated by Django 6.1.1 on 2026-10-06 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('standalone', 'Standalone'), ('group', 'Group')], default='standalone', max_length=20)),
                ('order_in_chapter', models.PositiveSmallIntegerField(default=0, verbose_name='Order In Chapter')),
                ('question_count', models.PositiveSmallIntegerField(default=0, verbose_name='Question Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_blocks', to='academic.chapter', verbose_name='Chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_blocks', to='academic.subject', verbose_name='Subject')),
                ('topics', models.ManyToManyField(blank=True, related_name='question_blocks', to='academic.topic')),
            ],
            options={
                'verbose_name': 'Question Block',
                'verbose_name_plural': 'Question Blocks',
                'ordering': ['order_in_chapter', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stimulus_type', models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('table', 'Table'), ('diagram', 'Diagram'), ('code', 'Code'), ('composite', 'Composite')], max_length=20)),
                ('stimulus_content', models.TextField(verbose_name='Stimulus')),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='question.questionblock')),
            ],
            options={
                'verbose_name': 'Question Set',
                'verbose_name_plural': 'Question Sets',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('cq', 'Creative Question')], default='mcq', max_length=20, verbose_name='Type')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Settings')),
                ('label', models.CharField(blank=True, max_length=8, verbose_name='Label')),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Marks')),
                ('order_in_set', models.PositiveSmallIntegerField(default=0, verbose_name='Order In Set')),
                ('prompt_content', models.TextField(verbose_name='Prompt')),
                ('model_answer', models.TextField(blank=True, verbose_name='Model Answer')),
                ('explanation', models.TextField(blank=True, verbose_name='Explanation')),
                ('block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_question', to='question.questionblock')),
                ('question_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question.questionset')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order_in_set', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('board', 'Board'), ('college', 'College'), ('university', 'University'), ('school', 'School'), ('other', 'Other')], default='board', max_length=20, verbose_name='Kind')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Question Source',
                'verbose_name_plural': 'Question Sources',
                'ordering': [models.OrderBy(models.F('year'), descending=True, nulls_last=True), 'kind', 'name'],
                'indexes': [models.Index(fields=['kind', 'year'], name='question_qu_kind_f180cf_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name', 'year', 'unit'), name='unique_question_source'), models.UniqueConstraint(condition=models.Q(('year__isnull', True)), fields=('kind', 'name', 'unit'), name='unique_undated_question_source')],
            },
        ),
        migrations.AddField(
            model_name='questionblock',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='question_blocks', to='question.questionsource'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=8, verbose_name='Label')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Correct')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question.question')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['question_id', 'position'],
                'constraints': [models.UniqueConstraint(fields=('question', 'position'), name='unique_option_position')],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_set', 'order_in_set'], name='question_qu_questio_bcfe76_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='question_qu_questio_a0dfc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('block__isnull', False), ('question_set__isnull', True)), models.Q(('block__isnull', True), ('question_set__isnull', False)), _connector='OR'), name='question_block_xor_set'),
        ),
        migrations.AddIndex(
            model_name='questionblock',
            index=models.Index(fields=['subject', 'chapter'], name='question_qu_subject_07523b_idx'),
        ),
        migrations.AddIndex(
            model_name='questionblock',
            index=models.Index(fields=['chapter', 'order_in_chapter'], name='question_qu_chapter_a9684f_idx'),
        ),
        migrations.AddIndex(
            model_name='questionblock',
            index=models.Index(fields=['kind'], name='question_qu_kind_133b66_idx'),
        ),
    ]
