# Generated by Django 5.0.14 on 2026-08-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('instructor', 'Instructor'), ('founder', 'Founder')], default='instructor', max_length=20)),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
