# Generated by Django 5.0.14 on 2026-08-16 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course'),
        ),
        migrations.AddField(
            model_name='noticecategory',
            name='notice_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.noticecategory'),
        ),
        migrations.AddField(
            model_name='notice',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='notices', to='cms.noticecategory'),
        ),
    ]
