# Generated by Django 5.0.14 on 2026-08-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_seed_home_pages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
