# Generated by Django 6.1.1 on 2026-10-06 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('phone_verify', 'Phone verification'), ('password_reset', 'Password reset'), ('expiry_reminder', 'Expiry reminder'), ('purchase', 'Purchase / renewal notice'), ('guardian', 'Message to a guardian'), ('custom', 'Custom message')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_received', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS message',
                'verbose_name_plural': 'SMS messages',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['purpose', 'created_at'], name='notificatio_purpose_0cf21b_idx'), models.Index(fields=['phone'], name='notificatio_phone_eefc07_idx')],
            },
        ),
    ]
