# Generated by Django 6.1.1 on 2026-10-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='purpose',
            field=models.CharField(choices=[('phone_verify', 'Phone verification'), ('password_reset', 'Password reset'), ('expiry_reminder', 'Expiry reminder'), ('access_ended', 'Access ended notice'), ('purchase', 'Purchase / renewal notice'), ('guardian', 'Message to a guardian'), ('custom', 'Custom message')], max_length=20),
        ),
    ]
